//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoServicesV2018.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Questions> Tbl_Questions { get; set; }
        public virtual DbSet<Tbl_QuestionsAns> Tbl_QuestionsAns { get; set; }
        public virtual DbSet<Tbl_QuestionsAns_New> Tbl_QuestionsAns_New { get; set; }
        public virtual DbSet<Tbl_QuestionsOptions> Tbl_QuestionsOptions { get; set; }
    }
}
