//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoServicesV2018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_QuestionsAns_New
    {
        public int AnsId { get; set; }
        public Nullable<int> QuetionId { get; set; }
        public Nullable<int> AnsValue { get; set; }
        public string AnsText { get; set; }
        public string FarmerName { get; set; }
        public string MobileNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
